config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  root controller: :index, action: :index

 resources :news, only: [:index, :show, :new, :create, :destroy, :update, :edit]

 resources :riders, only: [:index, :new, :create, :destroy, :edit, :update]

 get 'tags/:tag', to: 'news#index', as: "tag"

 namespace :api do
   namespace :v1 do
     resources :news, only: [:index, :show], defaults: { format: 'json'}
     resources :riders, only: [:index, :show], defaults: { format: 'json'}
   end
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/news.rb
class News < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).news
  end

  has_attached_file :file,
                      storage: :s3,
                      s3_credentials: Proc.new{|a| a.instance.s3_credentials }

  validates_attachment :file,
                        content_type:
                          {content_type: %w(image/jpg image/jpeg image/png image/gif)}

  def s3_credentials
  {
    bucket: 'tfz',
    access_key_id: ENV['AWS_ACCESS_KEY'],
    secret_access_key: ENV['AWS_SECRET_KEY'],
    s3_region: ENV['AWS_REGION'],
    url: ':s3_domain_url',
    s3_host_name: 's3-eu-west-1.amazonaws.com'
  }
  end

  validates_presence_of :title, :content
end

app/models/rider.rb
class Rider < ApplicationRecord
  validates_presence_of :name

  def self.search(term)
    if term
      where('name ILIKE ?', "%#{term}%").order(name: :asc)
    else
      all.order(name: :asc)
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :news, through: :taggings

  validates_presence_of :name
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :news
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  VALID_ROLES = ['admin', 'superadmin']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :role, inclusion: {in: VALID_ROLES, message: '%{value} is not a valid user role'}
end

app/controllers/api/v1/news_controller.rb
class Api::V1::NewsController < ApiController
  def index
    if params[:tag]
      @news = News.all.order(created_at: :desc).tagged_with(params[:tag]).order(created_at: :desc)
    else
      @news = News.all.order(created_at: :desc)
    end
  end

  def show
    begin
      @news = News.find(params[:id])
    rescue => error
      render json: { message: error}, status: 404
    end
  end
end

app/controllers/api/v1/riders_controller.rb
class Api::V1::RidersController < ApiController
  def index
    @riders = Rider.all.order(name: :asc)
  end

  def show
    begin
      @rider = Rider.find(params[:id])
    rescue => error
      render json: { message: error}, status: 404
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    if params[:tag]
      @news = News.all.order(created_at: :desc).tagged_with(params[:tag]).order(created_at: :desc)
    else
      @news = News.all.order(created_at: :desc)
    end
  end

  def show
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new news_params
    if @news.save
      flash[:notice] = 'News article created!'
      redirect_back(fallback_location: new_news_path)
    end
  end

  def destroy
    @news = News.find(params[:id])
    if @news.destroy
      flash[:notice] = 'News post deleted'
      redirect_back(fallback_location: news_path)
    end
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update news_params
      flash[:notice] = 'News post updated'
      redirect_back(fallback_location: news_path)
    end
  end

  private

  def news_params
    params.require(:news).permit(:title, :content, :file, :all_tags)
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  def index
    @riders = Rider.search(params[:term])
  end

  def new
    @rider = Rider.new
  end

  def create
    @rider = Rider.new rider_params
    if @rider.save
      flash[:notice] = 'New rider added'
      redirect_back(fallback_location: new_rider_path)
    end
  end

  def edit
    @rider = Rider.find(params[:id])
  end

  def destroy
    @rider = Rider.find(params[:id])
    if @rider.destroy
      flash[:notice] = 'Rider deleted'
      redirect_back(fallback_location: riders_path)
    end
  end

  def update
    @rider = Rider.find(params[:id])
    if @rider.update rider_params
      flash[:notice] = 'Rider updated'
      redirect_back(fallback_location: edit_rider_path)
    end
  end

  private

  def rider_params
    params.require(:rider).permit(:name, :ytlink, :vimeolink, :term)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end
end

app/views/index/index.html.erb
<h1>Backend for TFZ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title><%= content_for?(:title) ? yield(:title) : "TFZ" %></title>

        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= javascript_include_tag 'ckeditor/ckeditor.js' %>
    </head>

    <header class="sticky-shrinknav-header">
        <%= link_to image_tag('logo.jpg', size: "200"), root_path %>
        <ul class="menu sticky-shrinknav-menu">
            <li>
                <a href="/news">NEWS</a>
            </li>
            <li>
                <a href="/riders">RIDERS</a>
            </li>
            <li>
              <%= link_to 'SIGN OUT', destroy_user_session_path, {method: :delete} %>
            </li>
        </ul>
    </header>
    <hr>

    <body>
        <% if flash[:notice] %>
        <div class='notice'>
            <%= flash[:notice] %>
        </div>
        <% end %>
        <% if flash[:alert] %>
        <div class='alert'>
            <%= flash[:alert] %>
        </div>
        <% end %>
        <%= yield %>
    </body>

    <footer class="site-footer">
        <div class="row medium-unstack">
            <div class="medium-4 columns">
                <h4 class="site-footer-title">FOLLOW US</h4>
                <p>Lorem ipsum dolor sit amet.</p>
            </div>
            <div class="medium-4 columns">
                <h4 class="site-footer-title">USEFUL LINKS</h4>
            </div>
            <div class="medium-4 columns">
                <%= image_tag('footer-logo.png', size: "180") %>
            </div>
        </div>
    </footer>
</html>

app/views/news/edit.html.erb
<h2>Edit your news post</h2>
<p>Now editing: <%= @news.title %></p>
<%= form_for @news do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title, value: @news.title %>
  <div class='ckeditor'>
    <%= f.label  :content, 'Content' %>
    <%= f.cktext_area :content, value: @news.content, class: 'ckeditor' %>
  </div>
  <%= f.label :all_tags, 'Tags' %>
  <%= f.text_area :all_tags %>
  <%= f.label :file %>
  <%= f.file_field :file, value: @news.file %>
  <%= f.submit 'Submit', class: 'button inc' %>
<% end %>

app/views/news/index.html.erb
<div id='news'>
  <h1 class='titles'>NEWS</h1>
  <%= link_to 'Create news article', new_news_path, class: 'button inc' %>
    <% @news.each do |news| %>
      <div class='row'>
        <div class="news-<%= news.id %>">
          <div class='large-6 columns'>
            <div class='news-image'>
              <%= image_tag news.file.url, style: 'width: 300px; height: auto' %>
            </div>
          </div>
          <div class='news-title'>
            <%= link_to news.title, news_path(news)%>
          </div>
          <div class='news-content'>
            <%= news.content.html_safe %>
          </div>
          <div>
            <%= raw tag_links(news.all_tags) %>
          </div>
        </div>
      </div>
      <%= link_to 'Delete post', news_path(news), method: :delete, class: 'button tiny alert' %>
      <%= link_to 'Edit post', edit_news_path(news), class: 'button tiny default' %>
    <% end %>
</div>

app/views/news/new.html.erb
<h3>Create news post</h3>
<%= form_for @news do |f| %>
<%= f.label :title, 'Title' %>
<%= f.text_field :title %>
<div class='ckeditor'>
  <%= f.label  :content, 'Content' %>
  <%= f.cktext_area :content, class: 'ckeditor' %>
</div>
<%= f.label :all_tags, 'Tags' %>
<%= f.text_area :all_tags %>
<%= f.label :file %>
<%= f.file_field :file %>
<%= f.submit 'Submit', class: 'button inc' %>
<% end %>

app/views/news/show.html.erb
<div class='article-image'>
  <%= image_tag @news.file.url %>
</div>
<div class='article-title'>
  <h2><%= @news.title %></h2>
</div>
<div class='article-content'>
  <p><%= @news.content.html_safe %></p>
</div>
<div class='article-content'>
  <%= raw tag_links(@news.all_tags) %>
</div>

app/views/riders/edit.html.erb
<h2>Edit your Rider</h2>
<p>Now editing: <%= @rider.name %></p>
<%= form_for @rider do |f| %>
<%= f.label :name, 'Name' %>
<%= f.text_field :name, value: @rider.name %>
<%= f.label :ytlink, 'Youtube link' %>
<%= f.text_field :ytlink, value: @rider.ytlink %>
<%= f.label :vimeolink, 'Vimeo link' %>
<%= f.text_field :vimeolink, value: @rider.vimeolink %>
<%= f.submit 'Submit', class: 'button inc' %>
<% end %>

app/views/riders/index.html.erb
<h3>RIDER INDEX</h3>
<%= form_tag(riders_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<%= link_to 'Add rider', new_rider_path, class: 'button inc' %>
<% @riders.each do |rider| %>
  <div class='rider-name'>
    <p>NAME: <%= rider.name %> </p>
  </div>
  <div>
    <p>YOUTUBE LINK: <%= rider.ytlink %></p>
  </div>
  <div>
    <p>VIMEO LINK: <%= rider.vimeolink %></p>
  </div>
  <%= link_to 'Delete rider', rider_path(rider), method: :delete, class: 'button tiny alert' %>
  <%= link_to 'Edit rider', edit_rider_path(rider), class: 'button tiny default' %>
<% end %>

app/views/riders/new.html.erb
<h2>Add information about the rider</h2>
<%= form_for @rider do |f| %>
<%= f.label :name, 'Name' %>
<%= f.text_field :name %>
<%= f.label :ytlink, 'Youtube link' %>
<%= f.text_field :ytlink %>
<%= f.label :vimeolink, 'Vimeo link' %>
<%= f.text_field :vimeolink %>
<%= f.submit 'Submit', class: 'buttin inc' %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>